-- apagando banco de dados caso exista
DROP DATABASE IF EXISTS DBEXERCICIO14;
-- criando banco de dados
CREATE DATABASE DBEXERCICIO14;
-- conectando ao banco de dados
USE DBEXERCICIO13;
-- criandos as tabelas
CREATE TABLE CLIENTE (
IDCLIENTE INT NOT NULL AUTO_INCREMENT
, NOME VARCHAR(120) NOT NULL
, PRIMARY KEY (IDCLIENTE)
);

CREATE TABLE PRODUTO (
IDPEDIDO INT NOT NULL AUTO_INCREMENT
, NOME VARCHAR(50) NOT NULL
, IDCLIENTE INT NOT NULL
, PRIMARY KEY (IDPRODUTO)
);

CREATE TABLE PREFERENCIA (
IDCLIENTE INT NOT NULL
, IDPRODUTO INT NOT NULL
, PRIMARY KEY (IDCLIENTE, IDPRODUTO)
, FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE)
, FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO(IDPRODUTO)
);